CREATE TABLE MEDIAN_NOISE_LEVEL_PER_SENSOR (
    ID IDENTITY PRIMARY KEY,
    SENSOR_ID BIGINT NOT NULL,
    VALUE DECIMAL NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    CONSTRAINT FK_MEDIAN_NOISE_LEVEL_PER_SENSOR_ID FOREIGN KEY(SENSOR_ID) REFERENCES SENSOR(ID)
);